export type LayoutType = "classic" | "modern" | "bold" | "elegant" | "hero";
export type ButtonStyle = "rounded" | "sharp" | "soft" | "outline";
export type AvatarStyle = "circle" | "rounded" | "square";

export const TEMPLATES = [
  {
    id: "minimal",
    name: "Minimal",
    bg: "bg-[#f5f0eb]",
    cardBg: "bg-[#e8dfd6]",
    textColor: "text-[#4a3f35]",
    cardTextColor: "text-[#4a3f35]",
    accent: "#8b7355",
    description: "Clean and simple",
    layout: "classic" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "ocean",
    name: "Ocean",
    bg: "bg-gradient-to-b from-[#0f2027] via-[#203a43] to-[#2c5364]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#64ffda",
    description: "Deep blue vibes",
    layout: "hero" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "sunset",
    name: "Sunset",
    bg: "bg-gradient-to-b from-[#f093fb] via-[#f5576c] to-[#fda085]",
    cardBg: "bg-white/20",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#fff",
    description: "Warm gradients",
    layout: "bold" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "dark",
    name: "Midnight",
    bg: "bg-[#0a0a0a]",
    cardBg: "bg-[#1a1a1a]",
    textColor: "text-white",
    cardTextColor: "text-gray-200",
    accent: "#6C5CE7",
    description: "Sleek dark mode",
    layout: "modern" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "forest",
    name: "Forest",
    bg: "bg-gradient-to-b from-[#1a3c2a] to-[#2d5a3e]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#4ade80",
    description: "Nature inspired",
    layout: "elegant" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "lavender",
    name: "Lavender",
    bg: "bg-gradient-to-b from-[#e8dff5] to-[#fce4ec]",
    cardBg: "bg-white/60",
    textColor: "text-[#4a3068]",
    cardTextColor: "text-[#4a3068]",
    accent: "#7c3aed",
    description: "Soft purple tones",
    layout: "elegant" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "executive",
    name: "Executive",
    bg: "bg-gradient-to-b from-[#0c1824] to-[#152238]",
    cardBg: "bg-white/10",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#e8a838",
    description: "Bold corporate style",
    layout: "modern" as LayoutType,
    buttonStyle: "sharp" as ButtonStyle,
    avatarStyle: "square" as AvatarStyle,
  },
  {
    id: "crimson",
    name: "Crimson",
    bg: "bg-gradient-to-b from-[#b71c1c] via-[#c62828] to-[#1a1a2e]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#ff5252",
    description: "Bold red professional",
    layout: "bold" as LayoutType,
    buttonStyle: "sharp" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "amber",
    name: "Amber",
    bg: "bg-gradient-to-b from-[#f9a825] via-[#fbc02d] to-[#fff8e1]",
    cardBg: "bg-black/10",
    textColor: "text-[#3e2723]",
    cardTextColor: "text-[#3e2723]",
    accent: "#e65100",
    description: "Warm golden tones",
    layout: "classic" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "slate",
    name: "Slate",
    bg: "bg-gradient-to-b from-[#2c3e50] to-[#34495e]",
    cardBg: "bg-white/12",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#1abc9c",
    description: "Modern professional",
    layout: "hero" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "noir",
    name: "Noir",
    bg: "bg-gradient-to-b from-[#1a1a1a] via-[#2d2d2d] to-[#1a1a1a]",
    cardBg: "bg-white/8",
    textColor: "text-white",
    cardTextColor: "text-gray-200",
    accent: "#ffffff",
    description: "Classic monochrome",
    layout: "elegant" as LayoutType,
    buttonStyle: "outline" as ButtonStyle,
    avatarStyle: "square" as AvatarStyle,
  },
  {
    id: "coral",
    name: "Coral",
    bg: "bg-gradient-to-b from-[#ff6b6b] via-[#ee5a6f] to-[#f093fb]",
    cardBg: "bg-white/20",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#fff",
    description: "Vibrant and playful",
    layout: "bold" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "arctic",
    name: "Arctic",
    bg: "bg-gradient-to-b from-[#e3f2fd] via-[#bbdefb] to-[#e8eaf6]",
    cardBg: "bg-white/70",
    textColor: "text-[#1a237e]",
    cardTextColor: "text-[#1a237e]",
    accent: "#1565c0",
    description: "Cool and clean",
    layout: "classic" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "neon",
    name: "Neon",
    bg: "bg-gradient-to-b from-[#0d0221] via-[#150734] to-[#0d0221]",
    cardBg: "bg-[#1a0a3e]/80",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#00ff88",
    description: "Electric nightlife",
    layout: "hero" as LayoutType,
    buttonStyle: "outline" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "terracotta",
    name: "Terracotta",
    bg: "bg-gradient-to-b from-[#d4a373] via-[#c68b59] to-[#8b5e3c]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#fefae0",
    description: "Earthy warmth",
    layout: "modern" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "sapphire",
    name: "Sapphire",
    bg: "bg-gradient-to-b from-[#1e3a5f] via-[#1a5276] to-[#0e2a47]",
    cardBg: "bg-white/12",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#5dade2",
    description: "Deep blue elegance",
    layout: "elegant" as LayoutType,
    buttonStyle: "sharp" as ButtonStyle,
    avatarStyle: "square" as AvatarStyle,
  },
  {
    id: "rose",
    name: "Rose Gold",
    bg: "bg-gradient-to-b from-[#f4e4d7] via-[#e8c4b8] to-[#d4a59a]",
    cardBg: "bg-white/50",
    textColor: "text-[#5d3a3a]",
    cardTextColor: "text-[#5d3a3a]",
    accent: "#b76e79",
    description: "Elegant and warm",
    layout: "hero" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "lime",
    name: "Lime",
    bg: "bg-gradient-to-b from-[#a8e063] via-[#56ab2f] to-[#1e3a1e]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#cddc39",
    description: "Fresh and energetic",
    layout: "bold" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "glass",
    name: "Glass",
    bg: "bg-gradient-to-br from-[#667eea] via-[#764ba2] to-[#f093fb]",
    cardBg: "bg-white/20 backdrop-blur-lg border border-white/30",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#e0c3fc",
    description: "Frosted glassmorphism",
    layout: "hero" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "brutalist",
    name: "Brutalist",
    bg: "bg-[#f5f0e8]",
    cardBg: "bg-white border-2 border-black shadow-[4px_4px_0px_0px_#000]",
    textColor: "text-black",
    cardTextColor: "text-black",
    accent: "#ff3d00",
    description: "Raw bold design",
    layout: "classic" as LayoutType,
    buttonStyle: "sharp" as ButtonStyle,
    avatarStyle: "square" as AvatarStyle,
  },
  {
    id: "luxury",
    name: "Luxury",
    bg: "bg-gradient-to-b from-[#0c0c0c] via-[#1a1a1a] to-[#0c0c0c]",
    cardBg: "bg-[#1e1e1e] border border-[#c9a84c]/30",
    textColor: "text-[#f5e6c8]",
    cardTextColor: "text-[#f5e6c8]",
    accent: "#c9a84c",
    description: "Black & gold premium",
    layout: "elegant" as LayoutType,
    buttonStyle: "outline" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "aurora",
    name: "Aurora",
    bg: "bg-gradient-to-b from-[#0f0c29] via-[#302b63] to-[#24243e]",
    cardBg: "bg-white/10 backdrop-blur-md",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#00d2ff",
    description: "Northern lights glow",
    layout: "hero" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "retro",
    name: "Retro Y2K",
    bg: "bg-gradient-to-b from-[#ff6fd8] via-[#cd77ff] to-[#3baaff]",
    cardBg: "bg-white/30 border-2 border-white/50",
    textColor: "text-white",
    cardTextColor: "text-[#2a0845]",
    accent: "#ffe600",
    description: "Nostalgic 2000s vibes",
    layout: "bold" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "sakura",
    name: "Sakura",
    bg: "bg-gradient-to-b from-[#fce4ec] via-[#f8bbd0] to-[#fce4ec]",
    cardBg: "bg-white/70",
    textColor: "text-[#4a2040]",
    cardTextColor: "text-[#4a2040]",
    accent: "#e91e63",
    description: "Cherry blossom spring",
    layout: "elegant" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "mocha",
    name: "Mocha",
    bg: "bg-gradient-to-b from-[#3e2723] via-[#4e342e] to-[#3e2723]",
    cardBg: "bg-[#5d4037]/60",
    textColor: "text-[#efebe9]",
    cardTextColor: "text-[#efebe9]",
    accent: "#d7ccc8",
    description: "Warm coffee tones",
    layout: "modern" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "hologram",
    name: "Hologram",
    bg: "bg-gradient-to-br from-[#a18cd1] via-[#fbc2eb] to-[#a6c1ee]",
    cardBg: "bg-white/25 backdrop-blur-md border border-white/40",
    textColor: "text-[#2d1b69]",
    cardTextColor: "text-[#2d1b69]",
    accent: "#7c4dff",
    description: "Iridescent shimmer",
    layout: "modern" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "cloud",
    name: "Cloud",
    bg: "bg-gradient-to-b from-[#e0e7ff] via-[#f0f4ff] to-[#dbeafe]",
    cardBg: "bg-white/80",
    textColor: "text-[#334155]",
    cardTextColor: "text-[#334155]",
    accent: "#6366f1",
    description: "Airy and floating",
    layout: "classic" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "matrix",
    name: "Matrix",
    bg: "bg-[#050505]",
    cardBg: "bg-[#0a0a0a] border border-[#00ff41]/20",
    textColor: "text-[#00ff41]",
    cardTextColor: "text-[#00ff41]",
    accent: "#00ff41",
    description: "Digital code rain",
    layout: "modern" as LayoutType,
    buttonStyle: "sharp" as ButtonStyle,
    avatarStyle: "square" as AvatarStyle,
  },
  {
    id: "velvet",
    name: "Velvet",
    bg: "bg-gradient-to-b from-[#1a0533] via-[#2d0a4e] to-[#1a0533]",
    cardBg: "bg-[#3d1566]/60",
    textColor: "text-[#e1bee7]",
    cardTextColor: "text-[#e1bee7]",
    accent: "#ce93d8",
    description: "Rich jewel tones",
    layout: "elegant" as LayoutType,
    buttonStyle: "soft" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "dusk",
    name: "Dusk",
    bg: "bg-gradient-to-b from-[#ff7e5f] via-[#c56cd6] to-[#3b2667]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#ffab91",
    description: "Sunset to night sky",
    layout: "hero" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
  {
    id: "copper",
    name: "Copper",
    bg: "bg-gradient-to-b from-[#2c1810] via-[#3d2317] to-[#1a0f0a]",
    cardBg: "bg-[#3d2317]/70 border border-[#b87333]/25",
    textColor: "text-[#f5d6c3]",
    cardTextColor: "text-[#f5d6c3]",
    accent: "#b87333",
    description: "Warm metallic glow",
    layout: "bold" as LayoutType,
    buttonStyle: "outline" as ButtonStyle,
    avatarStyle: "rounded" as AvatarStyle,
  },
  {
    id: "candy",
    name: "Candy",
    bg: "bg-gradient-to-br from-[#ff9a9e] via-[#fecfef] to-[#fdfcfb]",
    cardBg: "bg-white/60 border border-pink-200/50",
    textColor: "text-[#6b2148]",
    cardTextColor: "text-[#6b2148]",
    accent: "#f06292",
    description: "Sweet and playful",
    layout: "classic" as LayoutType,
    buttonStyle: "rounded" as ButtonStyle,
    avatarStyle: "circle" as AvatarStyle,
  },
];

export type Template = (typeof TEMPLATES)[0];

export function getTemplate(id: string | null | undefined): Template {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}

export function getAvatarClass(style: AvatarStyle): string {
  switch (style) {
    case "circle": return "rounded-full";
    case "rounded": return "rounded-xl";
    case "square": return "rounded-md";
    default: return "rounded-full";
  }
}

export function getButtonClass(style: ButtonStyle): string {
  switch (style) {
    case "rounded": return "rounded-full";
    case "sharp": return "rounded-none";
    case "soft": return "rounded-xl";
    case "outline": return "rounded-xl border-2";
    default: return "rounded-xl";
  }
}

export const LAYOUT_LABELS: Record<LayoutType, string> = {
  classic: "Classic",
  modern: "Modern",
  bold: "Bold",
  elegant: "Elegant",
  hero: "Hero",
};
