export const TEMPLATES = [
  {
    id: "minimal",
    name: "Minimal",
    bg: "bg-[#f5f0eb]",
    cardBg: "bg-[#e8dfd6]",
    textColor: "text-[#4a3f35]",
    cardTextColor: "text-[#4a3f35]",
    accent: "#8b7355",
    description: "Clean and simple",
  },
  {
    id: "ocean",
    name: "Ocean",
    bg: "bg-gradient-to-b from-[#0f2027] via-[#203a43] to-[#2c5364]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#64ffda",
    description: "Deep blue vibes",
  },
  {
    id: "sunset",
    name: "Sunset",
    bg: "bg-gradient-to-b from-[#f093fb] via-[#f5576c] to-[#fda085]",
    cardBg: "bg-white/20",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#fff",
    description: "Warm gradients",
  },
  {
    id: "dark",
    name: "Midnight",
    bg: "bg-[#0a0a0a]",
    cardBg: "bg-[#1a1a1a]",
    textColor: "text-white",
    cardTextColor: "text-gray-200",
    accent: "#6C5CE7",
    description: "Sleek dark mode",
  },
  {
    id: "forest",
    name: "Forest",
    bg: "bg-gradient-to-b from-[#1a3c2a] to-[#2d5a3e]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#4ade80",
    description: "Nature inspired",
  },
  {
    id: "lavender",
    name: "Lavender",
    bg: "bg-gradient-to-b from-[#e8dff5] to-[#fce4ec]",
    cardBg: "bg-white/60",
    textColor: "text-[#4a3068]",
    cardTextColor: "text-[#4a3068]",
    accent: "#7c3aed",
    description: "Soft purple tones",
  },
  {
    id: "executive",
    name: "Executive",
    bg: "bg-gradient-to-b from-[#0c1824] to-[#152238]",
    cardBg: "bg-white/10",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#e8a838",
    description: "Bold corporate style",
  },
  {
    id: "crimson",
    name: "Crimson",
    bg: "bg-gradient-to-b from-[#b71c1c] via-[#c62828] to-[#1a1a2e]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#ff5252",
    description: "Bold red professional",
  },
  {
    id: "amber",
    name: "Amber",
    bg: "bg-gradient-to-b from-[#f9a825] via-[#fbc02d] to-[#fff8e1]",
    cardBg: "bg-black/10",
    textColor: "text-[#3e2723]",
    cardTextColor: "text-[#3e2723]",
    accent: "#e65100",
    description: "Warm golden tones",
  },
  {
    id: "slate",
    name: "Slate",
    bg: "bg-gradient-to-b from-[#2c3e50] to-[#34495e]",
    cardBg: "bg-white/12",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#1abc9c",
    description: "Modern professional",
  },
  {
    id: "noir",
    name: "Noir",
    bg: "bg-gradient-to-b from-[#1a1a1a] via-[#2d2d2d] to-[#1a1a1a]",
    cardBg: "bg-white/8",
    textColor: "text-white",
    cardTextColor: "text-gray-200",
    accent: "#ffffff",
    description: "Classic monochrome",
  },
  {
    id: "coral",
    name: "Coral",
    bg: "bg-gradient-to-b from-[#ff6b6b] via-[#ee5a6f] to-[#f093fb]",
    cardBg: "bg-white/20",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#fff",
    description: "Vibrant and playful",
  },
  {
    id: "arctic",
    name: "Arctic",
    bg: "bg-gradient-to-b from-[#e3f2fd] via-[#bbdefb] to-[#e8eaf6]",
    cardBg: "bg-white/70",
    textColor: "text-[#1a237e]",
    cardTextColor: "text-[#1a237e]",
    accent: "#1565c0",
    description: "Cool and clean",
  },
  {
    id: "neon",
    name: "Neon",
    bg: "bg-gradient-to-b from-[#0d0221] via-[#150734] to-[#0d0221]",
    cardBg: "bg-[#1a0a3e]/80",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#00ff88",
    description: "Electric nightlife",
  },
  {
    id: "terracotta",
    name: "Terracotta",
    bg: "bg-gradient-to-b from-[#d4a373] via-[#c68b59] to-[#8b5e3c]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#fefae0",
    description: "Earthy warmth",
  },
  {
    id: "sapphire",
    name: "Sapphire",
    bg: "bg-gradient-to-b from-[#1e3a5f] via-[#1a5276] to-[#0e2a47]",
    cardBg: "bg-white/12",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#5dade2",
    description: "Deep blue elegance",
  },
  {
    id: "rose",
    name: "Rose Gold",
    bg: "bg-gradient-to-b from-[#f4e4d7] via-[#e8c4b8] to-[#d4a59a]",
    cardBg: "bg-white/50",
    textColor: "text-[#5d3a3a]",
    cardTextColor: "text-[#5d3a3a]",
    accent: "#b76e79",
    description: "Elegant and warm",
  },
  {
    id: "lime",
    name: "Lime",
    bg: "bg-gradient-to-b from-[#a8e063] via-[#56ab2f] to-[#1e3a1e]",
    cardBg: "bg-white/15",
    textColor: "text-white",
    cardTextColor: "text-white",
    accent: "#cddc39",
    description: "Fresh and energetic",
  },
];

export type Template = (typeof TEMPLATES)[0];

export function getTemplate(id: string | null | undefined): Template {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0];
}
