import {
  Mail,
  Phone,
  Globe,
  Newspaper,
  Headphones,
  Music,
  Podcast,
  Palette,
  BookOpen,
  Cloud,
  Coffee,
  Radio,
  Users,
  MessageCircle,
  Dribbble,
  Languages,
  BookMarked,
  Link2,
  Heart,
  Map,
  Star,
  ShoppingBag,
  Image,
  Video,
  Gamepad2,
  Bike,
  Send,
  Hash,
  Tv,
  LucideIcon,
} from "lucide-react";
import {
  SiInstagram,
  SiX,
  SiFacebook,
  SiGithub,
  SiLinkedin,
  SiYoutube,
  SiTiktok,
  SiSpotify,
  SiDiscord,
  SiReddit,
  SiPinterest,
  SiSnapchat,
  SiTwitch,
  SiSoundcloud,
  SiTelegram,
  SiWhatsapp,
  SiMedium,
  SiPatreon,
  SiSteam,
  SiBehance,
  SiDribbble,
  SiVimeo,
  SiUnsplash,
  SiTumblr,
  SiSlack,
  SiSignal,
  SiBluesky,
  SiThreads,
  SiKofi,
  SiLastdotfm,
  SiMeetup,
  SiBandcamp,
  SiStrava,
  SiTidal,
  SiWechat,
} from "react-icons/si";
import { type ComponentType } from "react";

type IconComponent = LucideIcon | ComponentType<{ className?: string }>;

const PLATFORM_ICONS: Record<string, IconComponent> = {
  email: Mail,
  newsletter: Newspaper,
  phone: Phone,
  website: Globe,
  amazon: ShoppingBag,
  applemusic: Music,
  applepodcasts: Podcast,
  artstation: Palette,
  bandcamp: SiBandcamp,
  behance: SiBehance,
  bluesky: SiBluesky,
  caffeine: Coffee,
  clubhouse: Users,
  discord: SiDiscord,
  dribbble: SiDribbble,
  duolingo: Languages,
  facebook: SiFacebook,
  github: SiGithub,
  goodreads: BookMarked,
  googlepodcasts: Podcast,
  instagram: SiInstagram,
  kofi: SiKofi,
  lastfm: SiLastdotfm,
  linkedin: SiLinkedin,
  medium: SiMedium,
  meetup: SiMeetup,
  onlyfans: Star,
  patreon: SiPatreon,
  pinterest: SiPinterest,
  reddit: SiReddit,
  rednote: BookOpen,
  signal: SiSignal,
  slack: SiSlack,
  snapchat: SiSnapchat,
  soundcloud: SiSoundcloud,
  spotify: SiSpotify,
  steam: SiSteam,
  strava: SiStrava,
  telegram: SiTelegram,
  threads: SiThreads,
  tidal: SiTidal,
  tiktok: SiTiktok,
  tumblr: SiTumblr,
  twitch: SiTwitch,
  x: SiX,
  unsplash: SiUnsplash,
  vimeo: SiVimeo,
  wechat: SiWechat,
  whatsapp: SiWhatsapp,
  youtube: SiYoutube,
  youtubemusic: SiYoutube,
  youtubeshorts: SiYoutube,
};

export const BRAND_COLORS: Record<string, string> = {
  facebook: "#1877F2",
  instagram: "#E4405F",
  x: "#000000",
  linkedin: "#0A66C2",
  youtube: "#FF0000",
  youtubemusic: "#FF0000",
  youtubeshorts: "#FF0000",
  tiktok: "#000000",
  spotify: "#1DB954",
  discord: "#5865F2",
  reddit: "#FF4500",
  pinterest: "#E60023",
  snapchat: "#FFFC00",
  twitch: "#9146FF",
  soundcloud: "#FF5500",
  telegram: "#26A5E4",
  whatsapp: "#25D366",
  medium: "#000000",
  patreon: "#FF424D",
  steam: "#1B2838",
  behance: "#1769FF",
  dribbble: "#EA4C89",
  vimeo: "#1AB7EA",
  unsplash: "#000000",
  tumblr: "#36465D",
  slack: "#4A154B",
  signal: "#3A76F0",
  bluesky: "#0085FF",
  threads: "#000000",
  kofi: "#FF5E5B",
  lastfm: "#D51007",
  meetup: "#ED1C40",
  bandcamp: "#1DA0C3",
  strava: "#FC4C02",
  tidal: "#000000",
  wechat: "#07C160",
  github: "#181717",
  email: "#EA4335",
  phone: "#34A853",
  website: "#4285F4",
  amazon: "#FF9900",
  applemusic: "#FA243C",
  applepodcasts: "#9933CC",
  artstation: "#13AFF0",
  rednote: "#FE2C55",
};

export function SocialIcon({ platform, className, brandColor }: { platform: string; className?: string; brandColor?: boolean }) {
  const Icon = PLATFORM_ICONS[platform] || Link2;
  const color = brandColor ? BRAND_COLORS[platform] : undefined;
  return <Icon className={className || "w-4 h-4"} style={color ? { color } : undefined} />;
}
