import {
  Mail,
  Phone,
  Globe,
  Newspaper,
  Headphones,
  Music,
  Podcast,
  Palette,
  BookOpen,
  Cloud,
  Coffee,
  Radio,
  Users,
  MessageCircle,
  Dribbble,
  Languages,
  BookMarked,
  Link2,
  Heart,
  Map,
  Star,
  ShoppingBag,
  Image,
  Video,
  Gamepad2,
  Bike,
  Send,
  Hash,
  Tv,
  LucideIcon,
} from "lucide-react";
import {
  SiInstagram,
  SiX,
  SiFacebook,
  SiGithub,
  SiLinkedin,
  SiYoutube,
  SiTiktok,
  SiSpotify,
  SiDiscord,
  SiReddit,
  SiPinterest,
  SiSnapchat,
  SiTwitch,
  SiSoundcloud,
  SiTelegram,
  SiWhatsapp,
  SiMedium,
  SiPatreon,
  SiSteam,
  SiBehance,
  SiDribbble,
  SiVimeo,
  SiUnsplash,
  SiTumblr,
  SiSlack,
  SiSignal,
  SiBluesky,
  SiThreads,
  SiKofi,
  SiLastdotfm,
  SiMeetup,
  SiBandcamp,
  SiStrava,
  SiTidal,
  SiWechat,
} from "react-icons/si";
import { type ComponentType } from "react";

type IconComponent = LucideIcon | ComponentType<{ className?: string }>;

const PLATFORM_ICONS: Record<string, IconComponent> = {
  email: Mail,
  newsletter: Newspaper,
  phone: Phone,
  website: Globe,
  amazon: ShoppingBag,
  applemusic: Music,
  applepodcasts: Podcast,
  artstation: Palette,
  bandcamp: SiBandcamp,
  behance: SiBehance,
  bluesky: SiBluesky,
  caffeine: Coffee,
  clubhouse: Users,
  discord: SiDiscord,
  dribbble: SiDribbble,
  duolingo: Languages,
  facebook: SiFacebook,
  github: SiGithub,
  goodreads: BookMarked,
  googlepodcasts: Podcast,
  instagram: SiInstagram,
  kofi: SiKofi,
  lastfm: SiLastdotfm,
  linkedin: SiLinkedin,
  medium: SiMedium,
  meetup: SiMeetup,
  onlyfans: Star,
  patreon: SiPatreon,
  pinterest: SiPinterest,
  reddit: SiReddit,
  rednote: BookOpen,
  signal: SiSignal,
  slack: SiSlack,
  snapchat: SiSnapchat,
  soundcloud: SiSoundcloud,
  spotify: SiSpotify,
  steam: SiSteam,
  strava: SiStrava,
  telegram: SiTelegram,
  threads: SiThreads,
  tidal: SiTidal,
  tiktok: SiTiktok,
  tumblr: SiTumblr,
  twitch: SiTwitch,
  x: SiX,
  unsplash: SiUnsplash,
  vimeo: SiVimeo,
  wechat: SiWechat,
  whatsapp: SiWhatsapp,
  youtube: SiYoutube,
  youtubemusic: SiYoutube,
  youtubeshorts: SiYoutube,
};

export function SocialIcon({ platform, className }: { platform: string; className?: string }) {
  const Icon = PLATFORM_ICONS[platform] || Link2;
  return <Icon className={className || "w-4 h-4"} />;
}
